# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 350)
        MainWindow.setMinimumSize(QtCore.QSize(400, 350))
        MainWindow.setMaximumSize(QtCore.QSize(400, 350))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_id.setGeometry(QtCore.QRect(140, 50, 151, 21))
        self.input_id.setObjectName("input_id")
        self.label_id = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(100, 50, 16, 16))
        self.label_id.setObjectName("label_id")
        self.label_votingapplication = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_votingapplication.setGeometry(QtCore.QRect(130, 0, 141, 31))
        self.label_votingapplication.setObjectName("label_votingapplication")
        self.label_candidates = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_candidates.setGeometry(QtCore.QRect(160, 100, 91, 20))
        self.label_candidates.setObjectName("label_candidates")
        self.radioButton_jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_jane.setGeometry(QtCore.QRect(170, 140, 61, 20))
        self.radioButton_jane.setObjectName("radioButton_jane")
        self.radioButton_john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_john.setGeometry(QtCore.QRect(170, 170, 61, 20))
        self.radioButton_john.setObjectName("radioButton_john")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 210, 191, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_message.setGeometry(QtCore.QRect(80, 270, 251, 16))
        self.label_message.setText("")
        self.label_message.setObjectName("label_message")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting Application"))
        self.label_id.setText(_translate("MainWindow", "ID"))
        self.label_votingapplication.setText(_translate("MainWindow", "VOTING APPLICATION"))
        self.label_candidates.setText(_translate("MainWindow", "CANDIDATES"))
        self.radioButton_jane.setText(_translate("MainWindow", "Jane"))
        self.radioButton_john.setText(_translate("MainWindow", "John"))
        self.pushButton.setText(_translate("MainWindow", "SUBMIT VOTE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
